const PANEL_WIDTH_COLLAPSED = 20;
const PANEL_WIDTH_EXPANDED = 400;
const PANEL_WIDTH_EXPANDED_MOBILE = 100;
const PANEL_GAP = 15;
const PANEL_COUNT_DESKTOP = 20;
const PANEL_COUNT_MOBILE = 7;
const BREAKPOINT_MOBILE = 1000;

export {
  PANEL_WIDTH_COLLAPSED,
  PANEL_WIDTH_EXPANDED,
  PANEL_WIDTH_EXPANDED_MOBILE,
  PANEL_GAP,
  PANEL_COUNT_DESKTOP,
  PANEL_COUNT_MOBILE,
  BREAKPOINT_MOBILE,
};
